/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NewRouteImport } from './routes/new'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoyageTokenRouteImport } from './routes/voyage.$token'
import { Route as RoadbookPreviewMockRouteImport } from './routes/roadbook.preview-mock'
import { Route as RoadbookIdRouteImport } from './routes/roadbook.$id'
import { Route as ApiTrackViewRouteImport } from './routes/api/track-view'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiStripePortalRouteImport } from './routes/api/stripe-portal'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe-checkout'
import { Route as ApiSharedRoadbookRouteImport } from './routes/api/shared-roadbook'
import { Route as ApiRecomputeRoadbookRouteImport } from './routes/api/recompute-roadbook'
import { Route as ApiPexelsSearchRouteImport } from './routes/api/pexels-search'
import { Route as ApiMeSubscriptionRouteImport } from './routes/api/me-subscription'
import { Route as ApiMapsKeyRouteImport } from './routes/api/maps-key'
import { Route as ApiImportRoadbookRouteImport } from './routes/api/import-roadbook'
import { Route as ApiGeocodePlaceRouteImport } from './routes/api/geocode-place'
import { Route as ApiGenerateRoadbookRouteImport } from './routes/api/generate-roadbook'
import { Route as ApiDirectionsSegmentRouteImport } from './routes/api/directions-segment'
import { Route as ApiDestinationCoverRouteImport } from './routes/api/destination-cover'
import { Route as ApiChatRoadbookRouteImport } from './routes/api/chat-roadbook'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin-users'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoyageTokenRoute = VoyageTokenRouteImport.update({
  id: '/voyage/$token',
  path: '/voyage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadbookPreviewMockRoute = RoadbookPreviewMockRouteImport.update({
  id: '/roadbook/preview-mock',
  path: '/roadbook/preview-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadbookIdRoute = RoadbookIdRouteImport.update({
  id: '/roadbook/$id',
  path: '/roadbook/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackViewRoute = ApiTrackViewRouteImport.update({
  id: '/api/track-view',
  path: '/api/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe-portal',
  path: '/api/stripe-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe-checkout',
  path: '/api/stripe-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharedRoadbookRoute = ApiSharedRoadbookRouteImport.update({
  id: '/api/shared-roadbook',
  path: '/api/shared-roadbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecomputeRoadbookRoute = ApiRecomputeRoadbookRouteImport.update({
  id: '/api/recompute-roadbook',
  path: '/api/recompute-roadbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPexelsSearchRoute = ApiPexelsSearchRouteImport.update({
  id: '/api/pexels-search',
  path: '/api/pexels-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeSubscriptionRoute = ApiMeSubscriptionRouteImport.update({
  id: '/api/me-subscription',
  path: '/api/me-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapsKeyRoute = ApiMapsKeyRouteImport.update({
  id: '/api/maps-key',
  path: '/api/maps-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoadbookRoute = ApiImportRoadbookRouteImport.update({
  id: '/api/import-roadbook',
  path: '/api/import-roadbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodePlaceRoute = ApiGeocodePlaceRouteImport.update({
  id: '/api/geocode-place',
  path: '/api/geocode-place',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoadbookRoute = ApiGenerateRoadbookRouteImport.update({
  id: '/api/generate-roadbook',
  path: '/api/generate-roadbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectionsSegmentRoute = ApiDirectionsSegmentRouteImport.update({
  id: '/api/directions-segment',
  path: '/api/directions-segment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDestinationCoverRoute = ApiDestinationCoverRouteImport.update({
  id: '/api/destination-cover',
  path: '/api/destination-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoadbookRoute = ApiChatRoadbookRouteImport.update({
  id: '/api/chat-roadbook',
  path: '/api/chat-roadbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin-users',
  path: '/api/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/new': typeof NewRoute
  '/pricing': typeof PricingRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/chat-roadbook': typeof ApiChatRoadbookRoute
  '/api/destination-cover': typeof ApiDestinationCoverRoute
  '/api/directions-segment': typeof ApiDirectionsSegmentRoute
  '/api/generate-roadbook': typeof ApiGenerateRoadbookRoute
  '/api/geocode-place': typeof ApiGeocodePlaceRoute
  '/api/import-roadbook': typeof ApiImportRoadbookRoute
  '/api/maps-key': typeof ApiMapsKeyRoute
  '/api/me-subscription': typeof ApiMeSubscriptionRoute
  '/api/pexels-search': typeof ApiPexelsSearchRoute
  '/api/recompute-roadbook': typeof ApiRecomputeRoadbookRoute
  '/api/shared-roadbook': typeof ApiSharedRoadbookRoute
  '/api/stripe-checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe-portal': typeof ApiStripePortalRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/roadbook/$id': typeof RoadbookIdRoute
  '/roadbook/preview-mock': typeof RoadbookPreviewMockRoute
  '/voyage/$token': typeof VoyageTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/new': typeof NewRoute
  '/pricing': typeof PricingRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/chat-roadbook': typeof ApiChatRoadbookRoute
  '/api/destination-cover': typeof ApiDestinationCoverRoute
  '/api/directions-segment': typeof ApiDirectionsSegmentRoute
  '/api/generate-roadbook': typeof ApiGenerateRoadbookRoute
  '/api/geocode-place': typeof ApiGeocodePlaceRoute
  '/api/import-roadbook': typeof ApiImportRoadbookRoute
  '/api/maps-key': typeof ApiMapsKeyRoute
  '/api/me-subscription': typeof ApiMeSubscriptionRoute
  '/api/pexels-search': typeof ApiPexelsSearchRoute
  '/api/recompute-roadbook': typeof ApiRecomputeRoadbookRoute
  '/api/shared-roadbook': typeof ApiSharedRoadbookRoute
  '/api/stripe-checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe-portal': typeof ApiStripePortalRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/roadbook/$id': typeof RoadbookIdRoute
  '/roadbook/preview-mock': typeof RoadbookPreviewMockRoute
  '/voyage/$token': typeof VoyageTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/new': typeof NewRoute
  '/pricing': typeof PricingRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/chat-roadbook': typeof ApiChatRoadbookRoute
  '/api/destination-cover': typeof ApiDestinationCoverRoute
  '/api/directions-segment': typeof ApiDirectionsSegmentRoute
  '/api/generate-roadbook': typeof ApiGenerateRoadbookRoute
  '/api/geocode-place': typeof ApiGeocodePlaceRoute
  '/api/import-roadbook': typeof ApiImportRoadbookRoute
  '/api/maps-key': typeof ApiMapsKeyRoute
  '/api/me-subscription': typeof ApiMeSubscriptionRoute
  '/api/pexels-search': typeof ApiPexelsSearchRoute
  '/api/recompute-roadbook': typeof ApiRecomputeRoadbookRoute
  '/api/shared-roadbook': typeof ApiSharedRoadbookRoute
  '/api/stripe-checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe-portal': typeof ApiStripePortalRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/roadbook/$id': typeof RoadbookIdRoute
  '/roadbook/preview-mock': typeof RoadbookPreviewMockRoute
  '/voyage/$token': typeof VoyageTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/billing'
    | '/cgu'
    | '/confidentialite'
    | '/dashboard'
    | '/login'
    | '/mentions-legales'
    | '/new'
    | '/pricing'
    | '/profil'
    | '/reset-password'
    | '/api/admin-users'
    | '/api/chat-roadbook'
    | '/api/destination-cover'
    | '/api/directions-segment'
    | '/api/generate-roadbook'
    | '/api/geocode-place'
    | '/api/import-roadbook'
    | '/api/maps-key'
    | '/api/me-subscription'
    | '/api/pexels-search'
    | '/api/recompute-roadbook'
    | '/api/shared-roadbook'
    | '/api/stripe-checkout'
    | '/api/stripe-portal'
    | '/api/stripe-webhook'
    | '/api/track-view'
    | '/roadbook/$id'
    | '/roadbook/preview-mock'
    | '/voyage/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/billing'
    | '/cgu'
    | '/confidentialite'
    | '/dashboard'
    | '/login'
    | '/mentions-legales'
    | '/new'
    | '/pricing'
    | '/profil'
    | '/reset-password'
    | '/api/admin-users'
    | '/api/chat-roadbook'
    | '/api/destination-cover'
    | '/api/directions-segment'
    | '/api/generate-roadbook'
    | '/api/geocode-place'
    | '/api/import-roadbook'
    | '/api/maps-key'
    | '/api/me-subscription'
    | '/api/pexels-search'
    | '/api/recompute-roadbook'
    | '/api/shared-roadbook'
    | '/api/stripe-checkout'
    | '/api/stripe-portal'
    | '/api/stripe-webhook'
    | '/api/track-view'
    | '/roadbook/$id'
    | '/roadbook/preview-mock'
    | '/voyage/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/billing'
    | '/cgu'
    | '/confidentialite'
    | '/dashboard'
    | '/login'
    | '/mentions-legales'
    | '/new'
    | '/pricing'
    | '/profil'
    | '/reset-password'
    | '/api/admin-users'
    | '/api/chat-roadbook'
    | '/api/destination-cover'
    | '/api/directions-segment'
    | '/api/generate-roadbook'
    | '/api/geocode-place'
    | '/api/import-roadbook'
    | '/api/maps-key'
    | '/api/me-subscription'
    | '/api/pexels-search'
    | '/api/recompute-roadbook'
    | '/api/shared-roadbook'
    | '/api/stripe-checkout'
    | '/api/stripe-portal'
    | '/api/stripe-webhook'
    | '/api/track-view'
    | '/roadbook/$id'
    | '/roadbook/preview-mock'
    | '/voyage/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BillingRoute: typeof BillingRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  NewRoute: typeof NewRoute
  PricingRoute: typeof PricingRoute
  ProfilRoute: typeof ProfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiChatRoadbookRoute: typeof ApiChatRoadbookRoute
  ApiDestinationCoverRoute: typeof ApiDestinationCoverRoute
  ApiDirectionsSegmentRoute: typeof ApiDirectionsSegmentRoute
  ApiGenerateRoadbookRoute: typeof ApiGenerateRoadbookRoute
  ApiGeocodePlaceRoute: typeof ApiGeocodePlaceRoute
  ApiImportRoadbookRoute: typeof ApiImportRoadbookRoute
  ApiMapsKeyRoute: typeof ApiMapsKeyRoute
  ApiMeSubscriptionRoute: typeof ApiMeSubscriptionRoute
  ApiPexelsSearchRoute: typeof ApiPexelsSearchRoute
  ApiRecomputeRoadbookRoute: typeof ApiRecomputeRoadbookRoute
  ApiSharedRoadbookRoute: typeof ApiSharedRoadbookRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTrackViewRoute: typeof ApiTrackViewRoute
  RoadbookIdRoute: typeof RoadbookIdRoute
  RoadbookPreviewMockRoute: typeof RoadbookPreviewMockRoute
  VoyageTokenRoute: typeof VoyageTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voyage/$token': {
      id: '/voyage/$token'
      path: '/voyage/$token'
      fullPath: '/voyage/$token'
      preLoaderRoute: typeof VoyageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadbook/preview-mock': {
      id: '/roadbook/preview-mock'
      path: '/roadbook/preview-mock'
      fullPath: '/roadbook/preview-mock'
      preLoaderRoute: typeof RoadbookPreviewMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadbook/$id': {
      id: '/roadbook/$id'
      path: '/roadbook/$id'
      fullPath: '/roadbook/$id'
      preLoaderRoute: typeof RoadbookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-view': {
      id: '/api/track-view'
      path: '/api/track-view'
      fullPath: '/api/track-view'
      preLoaderRoute: typeof ApiTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-portal': {
      id: '/api/stripe-portal'
      path: '/api/stripe-portal'
      fullPath: '/api/stripe-portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-checkout': {
      id: '/api/stripe-checkout'
      path: '/api/stripe-checkout'
      fullPath: '/api/stripe-checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shared-roadbook': {
      id: '/api/shared-roadbook'
      path: '/api/shared-roadbook'
      fullPath: '/api/shared-roadbook'
      preLoaderRoute: typeof ApiSharedRoadbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recompute-roadbook': {
      id: '/api/recompute-roadbook'
      path: '/api/recompute-roadbook'
      fullPath: '/api/recompute-roadbook'
      preLoaderRoute: typeof ApiRecomputeRoadbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pexels-search': {
      id: '/api/pexels-search'
      path: '/api/pexels-search'
      fullPath: '/api/pexels-search'
      preLoaderRoute: typeof ApiPexelsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me-subscription': {
      id: '/api/me-subscription'
      path: '/api/me-subscription'
      fullPath: '/api/me-subscription'
      preLoaderRoute: typeof ApiMeSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maps-key': {
      id: '/api/maps-key'
      path: '/api/maps-key'
      fullPath: '/api/maps-key'
      preLoaderRoute: typeof ApiMapsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-roadbook': {
      id: '/api/import-roadbook'
      path: '/api/import-roadbook'
      fullPath: '/api/import-roadbook'
      preLoaderRoute: typeof ApiImportRoadbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode-place': {
      id: '/api/geocode-place'
      path: '/api/geocode-place'
      fullPath: '/api/geocode-place'
      preLoaderRoute: typeof ApiGeocodePlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-roadbook': {
      id: '/api/generate-roadbook'
      path: '/api/generate-roadbook'
      fullPath: '/api/generate-roadbook'
      preLoaderRoute: typeof ApiGenerateRoadbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/directions-segment': {
      id: '/api/directions-segment'
      path: '/api/directions-segment'
      fullPath: '/api/directions-segment'
      preLoaderRoute: typeof ApiDirectionsSegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/destination-cover': {
      id: '/api/destination-cover'
      path: '/api/destination-cover'
      fullPath: '/api/destination-cover'
      preLoaderRoute: typeof ApiDestinationCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-roadbook': {
      id: '/api/chat-roadbook'
      path: '/api/chat-roadbook'
      fullPath: '/api/chat-roadbook'
      preLoaderRoute: typeof ApiChatRoadbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-users': {
      id: '/api/admin-users'
      path: '/api/admin-users'
      fullPath: '/api/admin-users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BillingRoute: BillingRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  NewRoute: NewRoute,
  PricingRoute: PricingRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiChatRoadbookRoute: ApiChatRoadbookRoute,
  ApiDestinationCoverRoute: ApiDestinationCoverRoute,
  ApiDirectionsSegmentRoute: ApiDirectionsSegmentRoute,
  ApiGenerateRoadbookRoute: ApiGenerateRoadbookRoute,
  ApiGeocodePlaceRoute: ApiGeocodePlaceRoute,
  ApiImportRoadbookRoute: ApiImportRoadbookRoute,
  ApiMapsKeyRoute: ApiMapsKeyRoute,
  ApiMeSubscriptionRoute: ApiMeSubscriptionRoute,
  ApiPexelsSearchRoute: ApiPexelsSearchRoute,
  ApiRecomputeRoadbookRoute: ApiRecomputeRoadbookRoute,
  ApiSharedRoadbookRoute: ApiSharedRoadbookRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTrackViewRoute: ApiTrackViewRoute,
  RoadbookIdRoute: RoadbookIdRoute,
  RoadbookPreviewMockRoute: RoadbookPreviewMockRoute,
  VoyageTokenRoute: VoyageTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
