/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoadbookPreviewMockRouteImport } from './routes/roadbook.preview-mock'
import { Route as RoadbookIdRouteImport } from './routes/roadbook.$id'
import { Route as ApiRecomputeRoadbookRouteImport } from './routes/api/recompute-roadbook'
import { Route as ApiImportRoadbookRouteImport } from './routes/api/import-roadbook'
import { Route as ApiGenerateRoadbookRouteImport } from './routes/api/generate-roadbook'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadbookPreviewMockRoute = RoadbookPreviewMockRouteImport.update({
  id: '/roadbook/preview-mock',
  path: '/roadbook/preview-mock',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadbookIdRoute = RoadbookIdRouteImport.update({
  id: '/roadbook/$id',
  path: '/roadbook/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecomputeRoadbookRoute = ApiRecomputeRoadbookRouteImport.update({
  id: '/api/recompute-roadbook',
  path: '/api/recompute-roadbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoadbookRoute = ApiImportRoadbookRouteImport.update({
  id: '/api/import-roadbook',
  path: '/api/import-roadbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoadbookRoute = ApiGenerateRoadbookRouteImport.update({
  id: '/api/generate-roadbook',
  path: '/api/generate-roadbook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/api/generate-roadbook': typeof ApiGenerateRoadbookRoute
  '/api/import-roadbook': typeof ApiImportRoadbookRoute
  '/api/recompute-roadbook': typeof ApiRecomputeRoadbookRoute
  '/roadbook/$id': typeof RoadbookIdRoute
  '/roadbook/preview-mock': typeof RoadbookPreviewMockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/api/generate-roadbook': typeof ApiGenerateRoadbookRoute
  '/api/import-roadbook': typeof ApiImportRoadbookRoute
  '/api/recompute-roadbook': typeof ApiRecomputeRoadbookRoute
  '/roadbook/$id': typeof RoadbookIdRoute
  '/roadbook/preview-mock': typeof RoadbookPreviewMockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/api/generate-roadbook': typeof ApiGenerateRoadbookRoute
  '/api/import-roadbook': typeof ApiImportRoadbookRoute
  '/api/recompute-roadbook': typeof ApiRecomputeRoadbookRoute
  '/roadbook/$id': typeof RoadbookIdRoute
  '/roadbook/preview-mock': typeof RoadbookPreviewMockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/api/generate-roadbook'
    | '/api/import-roadbook'
    | '/api/recompute-roadbook'
    | '/roadbook/$id'
    | '/roadbook/preview-mock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/api/generate-roadbook'
    | '/api/import-roadbook'
    | '/api/recompute-roadbook'
    | '/roadbook/$id'
    | '/roadbook/preview-mock'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/api/generate-roadbook'
    | '/api/import-roadbook'
    | '/api/recompute-roadbook'
    | '/roadbook/$id'
    | '/roadbook/preview-mock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ApiGenerateRoadbookRoute: typeof ApiGenerateRoadbookRoute
  ApiImportRoadbookRoute: typeof ApiImportRoadbookRoute
  ApiRecomputeRoadbookRoute: typeof ApiRecomputeRoadbookRoute
  RoadbookIdRoute: typeof RoadbookIdRoute
  RoadbookPreviewMockRoute: typeof RoadbookPreviewMockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadbook/preview-mock': {
      id: '/roadbook/preview-mock'
      path: '/roadbook/preview-mock'
      fullPath: '/roadbook/preview-mock'
      preLoaderRoute: typeof RoadbookPreviewMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadbook/$id': {
      id: '/roadbook/$id'
      path: '/roadbook/$id'
      fullPath: '/roadbook/$id'
      preLoaderRoute: typeof RoadbookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recompute-roadbook': {
      id: '/api/recompute-roadbook'
      path: '/api/recompute-roadbook'
      fullPath: '/api/recompute-roadbook'
      preLoaderRoute: typeof ApiRecomputeRoadbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-roadbook': {
      id: '/api/import-roadbook'
      path: '/api/import-roadbook'
      fullPath: '/api/import-roadbook'
      preLoaderRoute: typeof ApiImportRoadbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-roadbook': {
      id: '/api/generate-roadbook'
      path: '/api/generate-roadbook'
      fullPath: '/api/generate-roadbook'
      preLoaderRoute: typeof ApiGenerateRoadbookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ApiGenerateRoadbookRoute: ApiGenerateRoadbookRoute,
  ApiImportRoadbookRoute: ApiImportRoadbookRoute,
  ApiRecomputeRoadbookRoute: ApiRecomputeRoadbookRoute,
  RoadbookIdRoute: RoadbookIdRoute,
  RoadbookPreviewMockRoute: RoadbookPreviewMockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
